//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuel_Consumption_Analysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public string CarID { get; set; }
        public string MarkID { get; set; }
        public string ModelID { get; set; }
        public double Consumption { get; set; }
        public double Distance { get; set; }
        public double Result { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual CarMarks CarMarks { get; set; }
        public virtual CarModels CarModels { get; set; }

        public string Model
        {
            get
            {
                return this.CarModels.Title;
            }
        }

        public string Mark
        {
            get
            {
                return this.CarMarks.Title;
            }
        }
    }
}
